-- =====================================================================
-- Exam Simulator: multi-track schema
-- Tables: tracks, exam_config, breaks, allowed_config, exams, enrollments
-- Constraints: enrollment overlap (EXCLUDE, needs btree_gist)
-- Triggers: break index vs question count
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS btree_gist;


-- ---------------------------------------------------------------------
-- tracks
-- ---------------------------------------------------------------------
CREATE TABLE public.tracks (
  id                        uuid     PRIMARY KEY DEFAULT gen_random_uuid(),
  name_ar                   text     NOT NULL,
  name_en                   text     NOT NULL,
  description_ar            text,
  description_en            text,
  enrollment_duration_days  smallint      NOT NULL CHECK (enrollment_duration_days > 0),
  created_at                timestamptz  NOT NULL DEFAULT now(),
  updated_at                timestamptz  NOT NULL DEFAULT now(),
  -- A description exists in both languages or in neither. A row with only one filled in would
  -- force the API to choose between dropping the language that exists and returning a half
  -- description, so the state is forbidden rather than handled.
  CONSTRAINT tracks_description_both_or_neither
    CHECK ((description_ar IS NULL) = (description_en IS NULL))
);


-- ---------------------------------------------------------------------
-- exam_type
-- ---------------------------------------------------------------------
CREATE TABLE public.exam_type (
  id          smallint     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_ar     text         NOT NULL,
  name_en     text         NOT NULL,
  colour      text,
  created_at  timestamptz  NOT NULL DEFAULT now(),
  updated_at  timestamptz  NOT NULL DEFAULT now()
);


-- ---------------------------------------------------------------------
-- exam_config
-- exam_duration_minutes: NULL = untimed
-- ---------------------------------------------------------------------
CREATE TABLE public.exam_config (
  id                     smallint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_ar                text          NOT NULL,
  name_en                text          NOT NULL,
  exam_duration_minutes  smallint      CHECK (exam_duration_minutes IS NULL OR exam_duration_minutes > 0),
  passing_rate           numeric(5,2)  NOT NULL CHECK (passing_rate BETWEEN 0 AND 100),
  can_reveal_answers     boolean       NOT NULL DEFAULT false,
  allow_retry_wrong      boolean       NOT NULL DEFAULT true,
  created_at             timestamptz   NOT NULL DEFAULT now(),
  updated_at             timestamptz   NOT NULL DEFAULT now()
);


-- ---------------------------------------------------------------------
-- breaks
-- duration: minutes
-- ---------------------------------------------------------------------
CREATE TABLE public.breaks (
  id                     smallint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_id              smallint  NOT NULL REFERENCES public.exam_config (id) ON DELETE CASCADE,
  show_at_index          smallint  NOT NULL CHECK (show_at_index >= 0),
  duration_minutes       smallint  NOT NULL CHECK (duration_minutes > 0),
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT breaks_config_id_show_at_index_key UNIQUE (config_id, show_at_index)
);


-- ---------------------------------------------------------------------
-- allowed_config
-- ---------------------------------------------------------------------
CREATE TABLE public.allowed_config (
  track_id   uuid      NOT NULL REFERENCES public.tracks (id)      ON DELETE CASCADE,
  config_id  smallint  NOT NULL REFERENCES public.exam_config (id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (track_id, config_id)
);


-- ---------------------------------------------------------------------
-- exams
-- (track_id, config_id) must be an allowed pair
-- ---------------------------------------------------------------------
CREATE TABLE public.exams (
  id              smallint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  track_id        uuid      NOT NULL,
  config_id       smallint  NOT NULL,
  type_id         smallint  NOT NULL REFERENCES public.exam_type (id) ON DELETE RESTRICT,
  display_order   smallint  GENERATED BY DEFAULT AS IDENTITY,
  name_ar         text      NOT NULL,
  name_en         text      NOT NULL,
  description_ar  text      NOT NULL,
  description_en  text      NOT NULL,
  question_count  smallint  NOT NULL CHECK (question_count > 0),
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT exams_track_id_display_order_key UNIQUE (track_id, display_order),
  CONSTRAINT exams_allowed_config_fkey
    FOREIGN KEY (track_id, config_id)
    REFERENCES public.allowed_config (track_id, config_id)
    ON DELETE RESTRICT
);


-- ---------------------------------------------------------------------
-- enrollments
-- ---------------------------------------------------------------------
CREATE TABLE public.enrollments (
  id          uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid         NOT NULL REFERENCES public.users (id)  ON DELETE CASCADE,
  track_id    uuid         NOT NULL REFERENCES public.tracks (id) ON DELETE RESTRICT,
  created_at  timestamptz  NOT NULL DEFAULT now(),
  expires_at  timestamptz  NOT NULL,
  updated_at  timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT enrollments_expires_after_created CHECK (expires_at > created_at)
);

-- No overlapping enrollments for the same user + track.
-- Ranges are [created_at, expires_at): a renewal starting exactly at
-- the previous expires_at is allowed. The GiST index behind this
-- constraint also serves (user_id, track_id) lookups.
ALTER TABLE public.enrollments
  ADD CONSTRAINT enrollments_no_overlap
  EXCLUDE USING gist (
    user_id  WITH =,
    track_id WITH =,
    tstzrange(created_at, expires_at) WITH &&
  );


-- =====================================================================
-- Trigger 2: break index must be strictly less than question_count
-- Checked from both sides: breaks and exams.
-- Both functions lock the shared exam_config row (FOR NO KEY UPDATE) so
-- a concurrent break insert and exam update cannot both pass.
-- =====================================================================

-- 2a. breaks side
CREATE FUNCTION public.breaks_check_index()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  PERFORM 1
  FROM public.exam_config c
  WHERE c.id = NEW.config_id
  FOR NO KEY UPDATE;

  IF EXISTS (
    SELECT 1
    FROM public.exams x
    WHERE x.config_id = NEW.config_id
      AND NEW.show_at_index >= x.question_count
  ) THEN
    RAISE EXCEPTION 'Break index % is not less than question_count of an exam using config %',
      NEW.show_at_index, NEW.config_id
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER breaks_check_index
BEFORE INSERT OR UPDATE OF config_id, show_at_index
ON public.breaks
FOR EACH ROW
EXECUTE FUNCTION public.breaks_check_index();


-- 2b. exams side
CREATE FUNCTION public.exams_check_break_index()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  PERFORM 1
  FROM public.exam_config c
  WHERE c.id = NEW.config_id
  FOR NO KEY UPDATE;

  IF EXISTS (
    SELECT 1
    FROM public.breaks b
    WHERE b.config_id = NEW.config_id
      AND b.show_at_index >= NEW.question_count
  ) THEN
    RAISE EXCEPTION 'Exam question_count % is not greater than a break index in config %',
      NEW.question_count, NEW.config_id
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER exams_check_break_index
BEFORE INSERT OR UPDATE OF config_id, question_count
ON public.exams
FOR EACH ROW
EXECUTE FUNCTION public.exams_check_break_index();


-- =====================================================================
-- updated_at maintenance
-- Reuses the existing public.handle_updated_at() function
-- (already used by public.users and public.exam_attempts)
-- =====================================================================
CREATE TRIGGER set_tracks_updated_at
BEFORE UPDATE ON public.tracks
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_exam_type_updated_at
BEFORE UPDATE ON public.exam_type
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_exam_config_updated_at
BEFORE UPDATE ON public.exam_config
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_breaks_updated_at
BEFORE UPDATE ON public.breaks
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_exams_updated_at
BEFORE UPDATE ON public.exams
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_enrollments_updated_at
BEFORE UPDATE ON public.enrollments
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();