-- =============================================================================
-- Migration 012: remap stored domain attempts onto the merged exam id space
--
-- Implements decision (10) of docs/specs/spec-add-tracks.md.
--
-- The domain question banks moved from src/data/exam/domain/<lang>/<n>.json to
-- src/data/exam/<lang>/<n + 17>.json, so every stored domain attempt has to
-- follow its exam. Full exam ids (1-17) are unchanged and are not touched here.
--
-- Must replay before 013_attempts_cleanup.sql: that migration drops
-- category_id - the only record of which domain an attempt belonged to - and
-- refuses to run while any domain attempt still has exam_id IS NULL.
--
-- Generated by scripts/migrate-exam-structure.py.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. chk_exam_type_domain (003) asserts domain => exam_id IS NULL. Writing the
--    remapped id violates it. The constraint guards a column pair that 013
--    removes outright, so it is dropped rather than rewritten.
-- ---------------------------------------------------------------------------
ALTER TABLE public.exam_attempts
  DROP CONSTRAINT chk_exam_type_domain;


-- ---------------------------------------------------------------------------
-- 2. Move each domain attempt onto its new exams row. category_id is left in
--    place for 013 to drop, so this statement stays re-runnable: rows already
--    carrying an exam_id are skipped.
-- ---------------------------------------------------------------------------
UPDATE public.exam_attempts
   SET exam_id = category_id + 17
 WHERE exam_type = 'domain'
   AND exam_id IS NULL;
