#!/usr/bin/env python3
"""
Flatten src/data/exam into a single per-language bank and merge the two exam
manifests into one.

    Before                              After
    ------                              -----
    exam/full-exams.json                exam/exams.json   (42 entries, typed)
    exam/categories.json                exam/exam-types.json (untouched)
    exam/full/<lang>/<id>.json          exam/<lang>/<id>.json
    exam/domain/<lang>/<id>.json        exam/<lang>/<id + 17>.json

Domain ids are shifted by DOMAIN_ID_OFFSET so they no longer collide with full
exam ids (1-17). Question file *contents* are never touched - files are moved
byte-for-byte.

Also emits the Postgres migration that moves stored domain attempts onto the
new id space (spec decision 10), and renumbers 012_attempts_cleanup.sql to 013
so the remap replays first.

Usage:
    python scripts/migrate-exam-structure.py            # dry run, prints the plan
    python scripts/migrate-exam-structure.py --apply    # perform the migration

Run from the repository root. Requires a clean working tree - the script
overwrites and deletes tracked files and does not implement an undo.
"""

import json
import shutil
import sys
from pathlib import Path

DOMAIN_ID_OFFSET = 17

REPO_ROOT = Path(__file__).resolve().parent.parent
EXAM_DIR = REPO_ROOT / "src" / "data" / "exam"
MIGRATIONS_DIR = REPO_ROOT / "supabase" / "migrations"

LANGS = ("en", "ar")

FULL_MANIFEST = EXAM_DIR / "full-exams.json"
DOMAIN_MANIFEST = EXAM_DIR / "categories.json"
MERGED_MANIFEST = EXAM_DIR / "exams.json"

CLEANUP_MIGRATION_OLD = MIGRATIONS_DIR / "012_attempts_cleanup.sql"
CLEANUP_MIGRATION_NEW = MIGRATIONS_DIR / "013_attempts_cleanup.sql"
REMAP_MIGRATION = MIGRATIONS_DIR / "012_remap_domain_exam_ids.sql"

REMAP_MIGRATION_SQL = f"""-- =============================================================================
-- Migration 012: remap stored domain attempts onto the merged exam id space
--
-- Implements decision (10) of docs/specs/spec-add-tracks.md.
--
-- The domain question banks moved from src/data/exam/domain/<lang>/<n>.json to
-- src/data/exam/<lang>/<n + {DOMAIN_ID_OFFSET}>.json, so every stored domain attempt has to
-- follow its exam. Full exam ids (1-17) are unchanged and are not touched here.
--
-- Must replay before 013_attempts_cleanup.sql: that migration drops
-- category_id - the only record of which domain an attempt belonged to - and
-- refuses to run while any domain attempt still has exam_id IS NULL.
--
-- Generated by scripts/migrate-exam-structure.py.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. chk_exam_type_domain (003) asserts domain => exam_id IS NULL. Writing the
--    remapped id violates it. The constraint guards a column pair that 013
--    removes outright, so it is dropped rather than rewritten.
-- ---------------------------------------------------------------------------
ALTER TABLE public.exam_attempts
  DROP CONSTRAINT chk_exam_type_domain;


-- ---------------------------------------------------------------------------
-- 2. Move each domain attempt onto its new exams row. category_id is left in
--    place for 013 to drop, so this statement stays re-runnable: rows already
--    carrying an exam_id are skipped.
-- ---------------------------------------------------------------------------
UPDATE public.exam_attempts
   SET exam_id = category_id + {DOMAIN_ID_OFFSET}
 WHERE exam_type = 'domain'
   AND exam_id IS NULL;
"""


class MigrationError(Exception):
    """A precondition failed; nothing has been written."""


def read_json(path):
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def write_json(path, data):
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(data, handle, ensure_ascii=False, indent=2)
        handle.write("\n")


def bank_path(exam_type, lang, exam_id):
    return EXAM_DIR / exam_type / lang / f"{exam_id}.json"


def target_path(lang, exam_id):
    return EXAM_DIR / lang / f"{exam_id}.json"


def build_plan():
    """Produce the merged manifest and the move list, or raise MigrationError."""
    if MERGED_MANIFEST.exists():
        raise MigrationError(f"{MERGED_MANIFEST.name} already exists - migration already applied")

    for path in (FULL_MANIFEST, DOMAIN_MANIFEST):
        if not path.exists():
            raise MigrationError(f"missing manifest: {path}")

    entries = []
    moves = []

    sources = (
        ("full", read_json(FULL_MANIFEST), 0),
        ("domain", read_json(DOMAIN_MANIFEST), DOMAIN_ID_OFFSET),
    )

    for exam_type, manifest, offset in sources:
        for entry in manifest:
            old_id = entry["id"]
            new_id = old_id + offset

            for lang in LANGS:
                source = bank_path(exam_type, lang, old_id)
                if not source.exists():
                    raise MigrationError(f"{exam_type} exam {old_id} has no {lang} bank: {source}")

                questions = read_json(source)
                if len(questions) != entry["questionCount"]:
                    raise MigrationError(
                        f"{source} holds {len(questions)} questions, "
                        f"manifest claims {entry['questionCount']}"
                    )

                moves.append((source, target_path(lang, new_id)))

            entries.append(
                {
                    "id": new_id,
                    "type": exam_type,
                    "name": entry["name"],
                    "questionCount": entry["questionCount"],
                }
            )

    assert_unique_ids(entries)
    assert_no_orphan_banks(entries)

    return entries, moves


def assert_unique_ids(entries):
    seen = {}
    for entry in entries:
        if entry["id"] in seen:
            raise MigrationError(
                f"id collision on {entry['id']}: "
                f"{seen[entry['id']]['type']} and {entry['type']} both claim it"
            )
        seen[entry["id"]] = entry


def assert_no_orphan_banks(entries):
    """Every bank file on disk must be claimed by a manifest entry."""
    claimed = {(exam_type, lang, entry["id"]) for entry in entries for lang in LANGS
               for exam_type in [entry["type"]]}

    for exam_type, offset in (("full", 0), ("domain", DOMAIN_ID_OFFSET)):
        for lang in LANGS:
            directory = EXAM_DIR / exam_type / lang
            for path in sorted(directory.glob("*.json")):
                exam_id = int(path.stem) + offset
                if (exam_type, lang, exam_id) not in claimed:
                    raise MigrationError(f"{path} is not listed in the manifest")


def apply_plan(entries, moves):
    for lang in LANGS:
        (EXAM_DIR / lang).mkdir(parents=True, exist_ok=True)

    for source, destination in moves:
        shutil.move(str(source), str(destination))

    write_json(MERGED_MANIFEST, entries)

    FULL_MANIFEST.unlink()
    DOMAIN_MANIFEST.unlink()

    for exam_type in ("full", "domain"):
        shutil.rmtree(EXAM_DIR / exam_type)


def apply_migrations():
    if REMAP_MIGRATION.exists():
        raise MigrationError(f"{REMAP_MIGRATION.name} already exists")
    if not CLEANUP_MIGRATION_OLD.exists():
        raise MigrationError(f"missing {CLEANUP_MIGRATION_OLD.name} - expected it at 012")

    shutil.move(str(CLEANUP_MIGRATION_OLD), str(CLEANUP_MIGRATION_NEW))

    with REMAP_MIGRATION.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(REMAP_MIGRATION_SQL)


def print_plan(entries, moves):
    print(f"{len(moves)} file moves ({len(entries)} exams x {len(LANGS)} languages):\n")
    for source, destination in moves:
        print(f"  {source.relative_to(EXAM_DIR)}  ->  {destination.relative_to(EXAM_DIR)}")

    print(f"\n{MERGED_MANIFEST.relative_to(REPO_ROOT)} ({len(entries)} entries):\n")
    for entry in entries:
        print(f"  {entry['id']:>3}  {entry['type']:<6}  {entry['questionCount']:>3}q  {entry['name']['en']}")

    print("\nmigrations:")
    print(f"  {CLEANUP_MIGRATION_OLD.name}  ->  {CLEANUP_MIGRATION_NEW.name}")
    print(f"  write {REMAP_MIGRATION.name}")

    print("\ndeleted:")
    for path in (FULL_MANIFEST, DOMAIN_MANIFEST):
        print(f"  {path.relative_to(REPO_ROOT)}")
    for exam_type in ("full", "domain"):
        print(f"  {(EXAM_DIR / exam_type).relative_to(REPO_ROOT)}/")


def main():
    apply = "--apply" in sys.argv[1:]

    try:
        entries, moves = build_plan()
    except MigrationError as error:
        print(f"refusing to migrate: {error}", file=sys.stderr)
        return 1

    print_plan(entries, moves)

    if not apply:
        print("\ndry run - nothing written. re-run with --apply")
        return 0

    try:
        apply_plan(entries, moves)
        apply_migrations()
    except MigrationError as error:
        print(f"\nmigration halted: {error}", file=sys.stderr)
        return 1

    print("\napplied.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
