-- =============================================================================
-- Migration 010: multi-track and question-content schema
--
-- DDL only. No content, no data migration — 011 carries the catalogue and 012
-- the question banks.
--
-- Consolidates what were three migrations while they were still unapplied
-- everywhere:
--   old 010  drop count_user_sessions
--   old 011  tracks / exam_type / exam_config / breaks / allowed_config /
--            exams / enrollments, plus the break-index and updated_at triggers
--   old 014  questions / choices / exam_questions
--
-- One behavioural difference from the originals, deliberate and noted at the
-- column: questions.answer_count is declared NOT NULL here rather than added
-- nullable, backfilled and tightened (old 022). The seed supplies it, so the
-- three-step dance had nothing to protect. The trigger that keeps it in step
-- lives at the end of 012, after the banks are loaded.
-- =============================================================================

-- Single-session enforcement moved to Supabase Auth ("Single session per user" in the
-- project's auth settings), so nothing calls this RPC any more. Drop it rather than leave a
-- security definer function that can read auth.sessions with no caller.
DROP FUNCTION IF EXISTS public.count_user_sessions(uuid);


CREATE EXTENSION IF NOT EXISTS btree_gist;


-- ---------------------------------------------------------------------
-- tracks
-- ---------------------------------------------------------------------
CREATE TABLE public.tracks (
  id                        uuid     PRIMARY KEY DEFAULT gen_random_uuid(),
  name_ar                   text     NOT NULL,
  name_en                   text     NOT NULL,
  description_ar            text,
  description_en            text,
  enrollment_duration_days  smallint      NOT NULL CHECK (enrollment_duration_days > 0),
  created_at                timestamptz  NOT NULL DEFAULT now(),
  updated_at                timestamptz  NOT NULL DEFAULT now(),
  -- A description exists in both languages or in neither. A row with only one filled in would
  -- force the API to choose between dropping the language that exists and returning a half
  -- description, so the state is forbidden rather than handled.
  CONSTRAINT tracks_description_both_or_neither
    CHECK ((description_ar IS NULL) = (description_en IS NULL))
);


-- ---------------------------------------------------------------------
-- exam_type
-- ---------------------------------------------------------------------
CREATE TABLE public.exam_type (
  id          smallint     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_ar     text         NOT NULL,
  name_en     text         NOT NULL,
  colour      text,
  created_at  timestamptz  NOT NULL DEFAULT now(),
  updated_at  timestamptz  NOT NULL DEFAULT now()
);


-- ---------------------------------------------------------------------
-- exam_config
-- exam_duration_minutes: NULL = untimed
-- ---------------------------------------------------------------------
CREATE TABLE public.exam_config (
  id                     smallint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_ar                text          NOT NULL,
  name_en                text          NOT NULL,
  exam_duration_minutes  smallint      CHECK (exam_duration_minutes IS NULL OR exam_duration_minutes > 0),
  passing_rate           numeric(5,2)  NOT NULL CHECK (passing_rate BETWEEN 0 AND 100),
  can_reveal_answers     boolean       NOT NULL DEFAULT false,
  allow_retry_wrong      boolean       NOT NULL DEFAULT true,
  created_at             timestamptz   NOT NULL DEFAULT now(),
  updated_at             timestamptz   NOT NULL DEFAULT now()
);


-- ---------------------------------------------------------------------
-- breaks
-- duration: minutes
-- ---------------------------------------------------------------------
CREATE TABLE public.breaks (
  id                     smallint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_id              smallint  NOT NULL REFERENCES public.exam_config (id) ON DELETE CASCADE,
  show_at_index          smallint  NOT NULL CHECK (show_at_index >= 0),
  duration_minutes       smallint  NOT NULL CHECK (duration_minutes > 0),
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT breaks_config_id_show_at_index_key UNIQUE (config_id, show_at_index)
);


-- ---------------------------------------------------------------------
-- allowed_config
-- ---------------------------------------------------------------------
CREATE TABLE public.allowed_config (
  track_id   uuid      NOT NULL REFERENCES public.tracks (id)      ON DELETE CASCADE,
  config_id  smallint  NOT NULL REFERENCES public.exam_config (id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (track_id, config_id)
);


-- ---------------------------------------------------------------------
-- exams
-- (track_id, config_id) must be an allowed pair
-- ---------------------------------------------------------------------
CREATE TABLE public.exams (
  id              smallint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  track_id        uuid      NOT NULL,
  config_id       smallint  NOT NULL,
  type_id         smallint  NOT NULL REFERENCES public.exam_type (id) ON DELETE RESTRICT,
  display_order   smallint  GENERATED BY DEFAULT AS IDENTITY,
  name_ar         text      NOT NULL,
  name_en         text      NOT NULL,
  description_ar  text      NOT NULL,
  description_en  text      NOT NULL,
  question_count  smallint  NOT NULL CHECK (question_count > 0),
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT exams_track_id_display_order_key UNIQUE (track_id, display_order),
  CONSTRAINT exams_allowed_config_fkey
    FOREIGN KEY (track_id, config_id)
    REFERENCES public.allowed_config (track_id, config_id)
    ON DELETE RESTRICT
);


-- ---------------------------------------------------------------------
-- enrollments
-- ---------------------------------------------------------------------
CREATE TABLE public.enrollments (
  id          uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid         NOT NULL REFERENCES public.users (id)  ON DELETE CASCADE,
  track_id    uuid         NOT NULL REFERENCES public.tracks (id) ON DELETE RESTRICT,
  created_at  timestamptz  NOT NULL DEFAULT now(),
  expires_at  timestamptz  NOT NULL,
  updated_at  timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT enrollments_expires_after_created CHECK (expires_at > created_at)
);

-- No overlapping enrollments for the same user + track.
-- Ranges are [created_at, expires_at): a renewal starting exactly at
-- the previous expires_at is allowed. The GiST index behind this
-- constraint also serves (user_id, track_id) lookups.
ALTER TABLE public.enrollments
  ADD CONSTRAINT enrollments_no_overlap
  EXCLUDE USING gist (
    user_id  WITH =,
    track_id WITH =,
    tstzrange(created_at, expires_at) WITH &&
  );


-- ---------------------------------------------------------------------------
-- questions
--
--    id is the existing bank id, reused verbatim. The id space is already
--    global and already consistent: across the bank files no id maps to two
--    different texts, so no remap is needed.
--
--    GENERATED BY DEFAULT AS IDENTITY, not plain integer: the seed supplies its
--    own ids, and a question authored later gets the next one without the
--    caller inventing it. 012 advances the sequence past the seeded maximum.
--    Same pattern as exams / exam_type / exam_config above.
--
--    answer_count is how many of a question's choices are correct. It is NOT
--    the answer key — a count, not a set of positions — so it is safe to select
--    on every read regardless of disclosure, and the UI reads it to decide
--    radio-vs-checkbox and to cap selection before the key is ever revealed.
--    Stored rather than counted per read, and kept true by the trigger created
--    at the end of 012.
-- ---------------------------------------------------------------------------
CREATE TABLE public.questions (
  id              integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type            text         NOT NULL,
  text_ar         text         NOT NULL,
  text_en         text         NOT NULL,
  explanation_ar  text         NOT NULL,
  explanation_en  text         NOT NULL,
  answer_count    smallint     NOT NULL,
  created_at      timestamptz  NOT NULL DEFAULT now(),
  updated_at      timestamptz  NOT NULL DEFAULT now(),

  CONSTRAINT questions_type_check CHECK (type IN ('multiple-choice')),
  CONSTRAINT chk_answer_count_positive CHECK (answer_count > 0)
);


-- ---------------------------------------------------------------------------
-- choices
--
--    position is the source order. Choices are never shuffled, so the stored
--    order IS the presentation order and the primary key can carry it.
-- ---------------------------------------------------------------------------
CREATE TABLE public.choices (
  question_id  integer   NOT NULL REFERENCES public.questions (id) ON DELETE CASCADE,
  position     smallint  NOT NULL CHECK (position >= 0),
  text_ar      text      NOT NULL,
  text_en      text      NOT NULL,
  is_correct   boolean   NOT NULL,

  PRIMARY KEY (question_id, position)
);


-- ---------------------------------------------------------------------------
-- exam_questions
--
--    A real many-to-many, not a 1:N in disguise: exams genuinely share
--    questions.
--
--    ON DELETE RESTRICT on question_id: a question that an exam still lists
--    must not vanish underneath it.
--
--    UNIQUE (exam_id, question_id) — no exam contains the same question twice —
--    is what makes attempt_answers' primary key (attempt_id, question_id) safe
--    in 013.
-- ---------------------------------------------------------------------------
CREATE TABLE public.exam_questions (
  exam_id         smallint  NOT NULL REFERENCES public.exams (id)     ON DELETE CASCADE,
  question_index  smallint  NOT NULL CHECK (question_index >= 0),
  question_id     integer   NOT NULL REFERENCES public.questions (id) ON DELETE RESTRICT,

  PRIMARY KEY (exam_id, question_index),
  CONSTRAINT exam_questions_exam_id_question_id_key UNIQUE (exam_id, question_id)
);

-- Serves the reverse lookup "which exams use this question", used by the
-- analytics queries in supabase/query/ and by the RESTRICT check above.
CREATE INDEX idx_exam_questions_question ON public.exam_questions (question_id);


-- =====================================================================
-- Trigger: break index must be strictly less than question_count
-- Checked from both sides: breaks and exams.
-- Both functions lock the shared exam_config row (FOR NO KEY UPDATE) so
-- a concurrent break insert and exam update cannot both pass.
-- =====================================================================

-- breaks side
CREATE FUNCTION public.breaks_check_index()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  PERFORM 1
  FROM public.exam_config c
  WHERE c.id = NEW.config_id
  FOR NO KEY UPDATE;

  IF EXISTS (
    SELECT 1
    FROM public.exams x
    WHERE x.config_id = NEW.config_id
      AND NEW.show_at_index >= x.question_count
  ) THEN
    RAISE EXCEPTION 'Break index % is not less than question_count of an exam using config %',
      NEW.show_at_index, NEW.config_id
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER breaks_check_index
BEFORE INSERT OR UPDATE OF config_id, show_at_index
ON public.breaks
FOR EACH ROW
EXECUTE FUNCTION public.breaks_check_index();


-- exams side
CREATE FUNCTION public.exams_check_break_index()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  PERFORM 1
  FROM public.exam_config c
  WHERE c.id = NEW.config_id
  FOR NO KEY UPDATE;

  IF EXISTS (
    SELECT 1
    FROM public.breaks b
    WHERE b.config_id = NEW.config_id
      AND b.show_at_index >= NEW.question_count
  ) THEN
    RAISE EXCEPTION 'Exam question_count % is not greater than a break index in config %',
      NEW.question_count, NEW.config_id
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER exams_check_break_index
BEFORE INSERT OR UPDATE OF config_id, question_count
ON public.exams
FOR EACH ROW
EXECUTE FUNCTION public.exams_check_break_index();


-- =====================================================================
-- updated_at maintenance
-- Reuses the existing public.handle_updated_at() function
-- (already used by public.users and public.exam_attempts)
--
-- choices and exam_questions are rewritten wholesale by a reseed rather
-- than edited in place, so neither carries the trigger.
-- =====================================================================
CREATE TRIGGER set_tracks_updated_at
BEFORE UPDATE ON public.tracks
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_exam_type_updated_at
BEFORE UPDATE ON public.exam_type
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_exam_config_updated_at
BEFORE UPDATE ON public.exam_config
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_breaks_updated_at
BEFORE UPDATE ON public.breaks
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_exams_updated_at
BEFORE UPDATE ON public.exams
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_enrollments_updated_at
BEFORE UPDATE ON public.enrollments
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_questions_updated_at
BEFORE UPDATE ON public.questions
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
