-- =============================================================================
-- Migration 011: track and exam catalogue
--
-- GENERATED by scripts/generate-content-migrations.py - do not edit by hand.
--
-- Content, not test data, and therefore a migration rather than a seed:
--   1. 013's config_snapshot backfill joins public.exams and public.exam_config.
--      Seeds run AFTER migrations, so with these rows in a seed the backfill
--      matches nothing and its SET NOT NULL fails on any database holding
--      attempts.
--   2. exam_questions (012) has a foreign key to public.exams. A seed cannot
--      satisfy a foreign key declared by a migration.
--
-- EXAMS 1, 3, 5 ARE ABSENT: their Arabic and English banks disagree
-- on the correct answer for eight questions. They share no question with any
-- other exam, so holding the whole exam back costs nothing else. Their
-- display_order values are left as gaps so they slot back into position when
-- a later migration restores them. See docs/specs/bank-conflicts.md.
--
--   tracks  2    exam_type  2    exam_config  2    exams  39
-- =============================================================================


-- ---------------------------------------------------------------------
-- tracks
--
-- The RMP track has no exams yet. It is created here so enrollments can
-- reference it and the UI can show it; its catalogue arrives in a later
-- migration alongside its banks.
-- ---------------------------------------------------------------------
INSERT INTO public.tracks (id, name_ar, name_en, description_ar, description_en, enrollment_duration_days)
VALUES
  ('33333333-3333-4333-8333-333333333333', 'محترف إدارة المشاريع (PMP)', 'Project Management Professional', 'امتحانات تجريبية وتدريبات مجالية لشهادة محترف إدارة المشاريع من PMI.', 'Practice exams and domain drills for the PMI Project Management Professional certification.', 180),
  ('44444444-4444-4444-8444-444444444444', 'محترف إدارة المخاطر (RMP)', 'Risk Management Professional', 'امتحانات تجريبية وتدريبات مجالية لشهادة محترف إدارة المخاطر من PMI.', 'Practice exams and domain drills for the PMI Risk Management Professional certification.', 180)
ON CONFLICT (id) DO NOTHING;


-- ---------------------------------------------------------------------
-- exam_type
-- ---------------------------------------------------------------------
INSERT INTO public.exam_type (id, name_ar, name_en, colour)
VALUES
  (1, 'امتحان كامل', 'Full Exam', 'primary'),
  (2, 'امتحان مجال (مصنف)', 'Domain Exam', 'secondary')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.exam_type', 'id'), coalesce((SELECT max(id) FROM public.exam_type), 1));


-- ---------------------------------------------------------------------
-- exam_config
--
-- exam_duration_minutes NULL = untimed. The domain config reveals answers as
-- the student goes, which makes it a study mode rather than a sitting, so it
-- carries no clock.
-- ---------------------------------------------------------------------
INSERT INTO public.exam_config (id, name_ar, name_en, exam_duration_minutes, passing_rate, can_reveal_answers, allow_retry_wrong)
VALUES
  (1, 'امتحان PMP الكامل', 'PMP Full Exam', 240, 75.00, false, true),
  (2, 'امتحان PMP المصنف', 'PMP Domain Exam', NULL, 85.00, true, false)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.exam_config', 'id'), coalesce((SELECT max(id) FROM public.exam_config), 1));


-- ---------------------------------------------------------------------
-- allowed_config
-- ---------------------------------------------------------------------
INSERT INTO public.allowed_config (track_id, config_id)
VALUES
  ('33333333-3333-4333-8333-333333333333', 1),
  ('33333333-3333-4333-8333-333333333333', 2)
ON CONFLICT (track_id, config_id) DO NOTHING;


-- ---------------------------------------------------------------------
-- breaks
--
-- Inserted BEFORE exams, and the order is load-bearing: breaks_check_index
-- scans exams for a conflicting question_count, and exams_check_break_index
-- scans breaks. Inserting exams first would validate each break against exams
-- that already exist, which is the case that raises.
-- ---------------------------------------------------------------------
INSERT INTO public.breaks (config_id, show_at_index, duration_minutes)
VALUES
  (1, 60, 10),
  (1, 120, 10)
ON CONFLICT (config_id, show_at_index) DO NOTHING;


-- ---------------------------------------------------------------------
-- exams
--
-- display_order follows src/data/exam/exams.json, which is the order the
-- list is meant to read in. 1, 3, 5 are skipped, leaving their positions free.
-- question_count is counted from the banks, not copied from exams.json, and
-- is the same number the description quotes.
-- ---------------------------------------------------------------------
INSERT INTO public.exams (id, track_id, config_id, type_id, display_order, name_ar, name_en, description_ar, description_en, question_count)
VALUES
  (17, '33333333-3333-4333-8333-333333333333', 1, 1, 1, 'اختبار PMP Aug 2026', 'PMP Aug 2026', 'امتحان كامل من 178 سؤالًا يغطي مجالات PMP الثلاثة، بمدة 4 ساعات واستراحتين.', '178 questions across the three PMP domains, timed at 4 hours with two scheduled breaks.', 178),
  (16, '33333333-3333-4333-8333-333333333333', 1, 1, 2, 'اختبار PMP Core 2026', 'PMP Core 2026', 'امتحان كامل من 185 سؤالًا يغطي مجالات PMP الثلاثة، بمدة 4 ساعات واستراحتين.', '185 questions across the three PMP domains, timed at 4 hours with two scheduled breaks.', 185),
  (10, '33333333-3333-4333-8333-333333333333', 1, 1, 3, 'اختبار PMI 1', 'PMI Exam 1', 'امتحان كامل من 180 سؤالًا يغطي مجالات PMP الثلاثة، بمدة 4 ساعات واستراحتين.', '180 questions across the three PMP domains, timed at 4 hours with two scheduled breaks.', 180),
  (14, '33333333-3333-4333-8333-333333333333', 1, 1, 4, 'اختبار PMI 2', 'PMI Exam 2', 'امتحان كامل من 180 سؤالًا يغطي مجالات PMP الثلاثة، بمدة 4 ساعات واستراحتين.', '180 questions across the three PMP domains, timed at 4 hours with two scheduled breaks.', 180),
  (15, '33333333-3333-4333-8333-333333333333', 1, 1, 5, 'اختبار PMI 3', 'PMI Exam 3', 'امتحان كامل من 180 سؤالًا يغطي مجالات PMP الثلاثة، بمدة 4 ساعات واستراحتين.', '180 questions across the three PMP domains, timed at 4 hours with two scheduled breaks.', 180),
  (12, '33333333-3333-4333-8333-333333333333', 1, 1, 6, 'اختبار PMP ECO الكامل 1', 'PMP Full Exam ECO 1', 'امتحان كامل من 180 سؤالًا يغطي مجالات PMP الثلاثة، بمدة 4 ساعات واستراحتين.', '180 questions across the three PMP domains, timed at 4 hours with two scheduled breaks.', 180),
  (13, '33333333-3333-4333-8333-333333333333', 1, 1, 7, 'اختبار PMP ECO الكامل 2', 'PMP Full Exam ECO 2', 'امتحان كامل من 175 سؤالًا يغطي مجالات PMP الثلاثة، بمدة 4 ساعات واستراحتين.', '175 questions across the three PMP domains, timed at 4 hours with two scheduled breaks.', 175),
  (2, '33333333-3333-4333-8333-333333333333', 1, 1, 9, 'اختبار PMP الكامل 2', 'PMP Full Exam 2', 'امتحان كامل من 175 سؤالًا يغطي مجالات PMP الثلاثة، بمدة 4 ساعات واستراحتين.', '175 questions across the three PMP domains, timed at 4 hours with two scheduled breaks.', 175),
  (4, '33333333-3333-4333-8333-333333333333', 1, 1, 11, 'اختبار PMP الكامل 4', 'PMP Full Exam 4', 'امتحان كامل من 175 سؤالًا يغطي مجالات PMP الثلاثة، بمدة 4 ساعات واستراحتين.', '175 questions across the three PMP domains, timed at 4 hours with two scheduled breaks.', 175),
  (6, '33333333-3333-4333-8333-333333333333', 1, 1, 13, 'اختبار PMP التجريبي 1', 'PMP Mock Exam 1', 'امتحان كامل من 181 سؤالًا يغطي مجالات PMP الثلاثة، بمدة 4 ساعات واستراحتين.', '181 questions across the three PMP domains, timed at 4 hours with two scheduled breaks.', 181),
  (7, '33333333-3333-4333-8333-333333333333', 1, 1, 14, 'اختبار PMP التجريبي 2', 'PMP Mock Exam 2', 'امتحان كامل من 181 سؤالًا يغطي مجالات PMP الثلاثة، بمدة 4 ساعات واستراحتين.', '181 questions across the three PMP domains, timed at 4 hours with two scheduled breaks.', 181),
  (8, '33333333-3333-4333-8333-333333333333', 1, 1, 15, 'اختبار PMP التجريبي 3', 'PMP Mock Exam 3', 'امتحان كامل من 181 سؤالًا يغطي مجالات PMP الثلاثة، بمدة 4 ساعات واستراحتين.', '181 questions across the three PMP domains, timed at 4 hours with two scheduled breaks.', 181),
  (9, '33333333-3333-4333-8333-333333333333', 1, 1, 16, 'اختبار PMP التجريبي 4', 'PMP Mock Exam 4', 'امتحان كامل من 181 سؤالًا يغطي مجالات PMP الثلاثة، بمدة 4 ساعات واستراحتين.', '181 questions across the three PMP domains, timed at 4 hours with two scheduled breaks.', 181),
  (43, '33333333-3333-4333-8333-333333333333', 2, 2, 17, 'أسئلة الذكاء الاصطناعي', 'AI Questions', 'تدريب من 10 أسئلة بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '10 untimed practice questions, with the correct answer and explanation shown after each one.', 10),
  (42, '33333333-3333-4333-8333-333333333333', 2, 2, 18, 'دراسات حالة', 'Case Studies', 'تدريب من 18 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '18 untimed practice questions, with the correct answer and explanation shown after each one.', 18),
  (18, '33333333-3333-4333-8333-333333333333', 2, 2, 19, 'الميزانية', 'Budget', 'تدريب من 46 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '46 untimed practice questions, with the correct answer and explanation shown after each one.', 46),
  (19, '33333333-3333-4333-8333-333333333333', 2, 2, 20, 'بناء مشترك', 'Building Shared', 'تدريب من 21 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '21 untimed practice questions, with the correct answer and explanation shown after each one.', 21),
  (20, '33333333-3333-4333-8333-333333333333', 2, 2, 21, 'التواصل', 'Communication', 'تدريب من 16 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '16 untimed practice questions, with the correct answer and explanation shown after each one.', 16),
  (21, '33333333-3333-4333-8333-333333333333', 2, 2, 22, 'قيادة فريق', 'Leading A Team', 'تدريب من 58 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '58 untimed practice questions, with the correct answer and explanation shown after each one.', 58),
  (22, '33333333-3333-4333-8333-333333333333', 2, 2, 23, 'التغييرات التنظيمية', 'Organizational Changes', 'تدريب من 21 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '21 untimed practice questions, with the correct answer and explanation shown after each one.', 21),
  (23, '33333333-3333-4333-8333-333333333333', 2, 2, 24, 'الجودة', 'Quality', 'تدريب من 44 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '44 untimed practice questions, with the correct answer and explanation shown after each one.', 44),
  (24, '33333333-3333-4333-8333-333333333333', 2, 2, 25, 'الموارد', 'Resources', 'تدريب من 22 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '22 untimed practice questions, with the correct answer and explanation shown after each one.', 22),
  (25, '33333333-3333-4333-8333-333333333333', 2, 2, 26, 'المخاطر', 'Risk', 'تدريب من 94 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '94 untimed practice questions, with the correct answer and explanation shown after each one.', 94),
  (26, '33333333-3333-4333-8333-333333333333', 2, 2, 27, 'النطاق', 'Scope', 'تدريب من 35 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '35 untimed practice questions, with the correct answer and explanation shown after each one.', 35),
  (27, '33333333-3333-4333-8333-333333333333', 2, 2, 28, 'الجدول الزمني', 'Schedule', 'تدريب من 47 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '47 untimed practice questions, with the correct answer and explanation shown after each one.', 47),
  (28, '33333333-3333-4333-8333-333333333333', 2, 2, 29, 'أصحاب المصلحة (المعنيين)', 'Stakeholders', 'تدريب من 18 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '18 untimed practice questions, with the correct answer and explanation shown after each one.', 18),
  (29, '33333333-3333-4333-8333-333333333333', 2, 2, 30, 'المشتريات', 'Procurement', 'تدريب من 50 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '50 untimed practice questions, with the correct answer and explanation shown after each one.', 50),
  (30, '33333333-3333-4333-8333-333333333333', 2, 2, 31, 'الامتثال', 'Compliance', 'تدريب من 25 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '25 untimed practice questions, with the correct answer and explanation shown after each one.', 25),
  (31, '33333333-3333-4333-8333-333333333333', 2, 2, 32, 'التغييرات الخارجية', 'External Changes', 'تدريب من 17 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '17 untimed practice questions, with the correct answer and explanation shown after each one.', 17),
  (32, '33333333-3333-4333-8333-333333333333', 2, 2, 33, 'الإغلاق', 'Closure Transition', 'تدريب من 18 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '18 untimed practice questions, with the correct answer and explanation shown after each one.', 18),
  (33, '33333333-3333-4333-8333-333333333333', 2, 2, 34, 'عناصر العمل', 'Artifacts', 'تدريب من 27 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '27 untimed practice questions, with the correct answer and explanation shown after each one.', 27),
  (34, '33333333-3333-4333-8333-333333333333', 2, 2, 35, 'التغييرات', 'Changes', 'تدريب من 42 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '42 untimed practice questions, with the correct answer and explanation shown after each one.', 42),
  (35, '33333333-3333-4333-8333-333333333333', 2, 2, 36, 'التعاون مع أصحاب المصلحة', 'Collaborating with Stakeholders', 'تدريب من 52 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '52 untimed practice questions, with the correct answer and explanation shown after each one.', 52),
  (36, '33333333-3333-4333-8333-333333333333', 2, 2, 37, 'تقوية أصحاب المصلحة', 'Empowering Stakeholders', 'تدريب من 15 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '15 untimed practice questions, with the correct answer and explanation shown after each one.', 15),
  (37, '33333333-3333-4333-8333-333333333333', 2, 2, 38, 'إدارة النزاعات', 'Managing Conflicts', 'تدريب من 17 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '17 untimed practice questions, with the correct answer and explanation shown after each one.', 17),
  (38, '33333333-3333-4333-8333-333333333333', 2, 2, 39, 'المنهجية', 'Methodology', 'تدريب من 48 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '48 untimed practice questions, with the correct answer and explanation shown after each one.', 48),
  (39, '33333333-3333-4333-8333-333333333333', 2, 2, 40, 'التخطيط', 'Planning', 'تدريب من 10 أسئلة بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '10 untimed practice questions, with the correct answer and explanation shown after each one.', 10),
  (40, '33333333-3333-4333-8333-333333333333', 2, 2, 41, 'القيمة', 'Value', 'تدريب من 37 سؤالًا بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '37 untimed practice questions, with the correct answer and explanation shown after each one.', 37),
  (41, '33333333-3333-4333-8333-333333333333', 2, 2, 42, 'المنهجية المرنة (أجايل)', 'Agile', 'تدريب من 200 سؤال بدون توقيت، مع عرض الإجابة الصحيحة والشرح بعد كل سؤال.', '200 untimed practice questions, with the correct answer and explanation shown after each one.', 200)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.exams', 'id'), coalesce((SELECT max(id) FROM public.exams), 1));
SELECT setval(pg_get_serial_sequence('public.exams', 'display_order'), coalesce((SELECT max(display_order) FROM public.exams), 1));
