-- =============================================================================
-- Migration 014: question content tables
--
-- The question banks leave the JavaScript bundle and become rows
-- (spec-add-tracks-api.md section 6). This migration is DDL only; 015 carries
-- the generated data.
--
-- Language lives in columns, not rows: the ar and en banks are perfectly
-- parallel — identical length and identical id-per-index in every one of the
-- 42 files, verified by scripts/analyze-banks.py (6.5).
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. questions
--
--    id is the existing bank id, reused verbatim. The id space is already
--    global and already consistent: across all 42 files no id maps to two
--    different texts (6.3), so no remap is needed.
--
--    GENERATED BY DEFAULT AS IDENTITY, not plain integer: the seed supplies its
--    own ids, and a question authored later gets the next one without the
--    caller inventing it. 015 advances the sequence past the seeded maximum.
--    Same pattern as exams / exam_type / exam_config in 011.
-- ---------------------------------------------------------------------------
CREATE TABLE public.questions (
  id              integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type            text         NOT NULL,
  text_ar         text         NOT NULL,
  text_en         text         NOT NULL,
  explanation_ar  text         NOT NULL,
  explanation_en  text         NOT NULL,
  created_at      timestamptz  NOT NULL DEFAULT now(),
  updated_at      timestamptz  NOT NULL DEFAULT now(),

  CONSTRAINT questions_type_check CHECK (type IN ('multiple-choice'))
);


-- ---------------------------------------------------------------------------
-- 2. choices
--
--    position is the source order. Choices are never shuffled (013 dropped
--    choices_order), so the stored order IS the presentation order and the
--    primary key can carry it.
-- ---------------------------------------------------------------------------
CREATE TABLE public.choices (
  question_id  integer   NOT NULL REFERENCES public.questions (id) ON DELETE CASCADE,
  position     smallint  NOT NULL CHECK (position >= 0),
  text_ar      text      NOT NULL,
  text_en      text      NOT NULL,
  is_correct   boolean   NOT NULL,

  PRIMARY KEY (question_id, position)
);


-- ---------------------------------------------------------------------------
-- 3. exam_questions
--
--    A real many-to-many, not a 1:N in disguise: 3,865 instances over 3,138
--    distinct ids — exams genuinely share questions (6.2).
--
--    ON DELETE RESTRICT on question_id: a question that an exam still lists
--    must not vanish underneath it.
--
--    UNIQUE (exam_id, question_id) encodes 6.4 — no exam contains the same
--    question twice — which is what makes attempt_answers' new primary key
--    (attempt_id, question_id) safe in 016.
-- ---------------------------------------------------------------------------
CREATE TABLE public.exam_questions (
  exam_id         smallint  NOT NULL REFERENCES public.exams (id)     ON DELETE CASCADE,
  question_index  smallint  NOT NULL CHECK (question_index >= 0),
  question_id     integer   NOT NULL REFERENCES public.questions (id) ON DELETE RESTRICT,

  PRIMARY KEY (exam_id, question_index),
  CONSTRAINT exam_questions_exam_id_question_id_key UNIQUE (exam_id, question_id)
);

-- Serves the reverse lookup "which exams use this question", used by the
-- analytics queries in supabase/query/ and by the RESTRICT check above.
CREATE INDEX idx_exam_questions_question ON public.exam_questions (question_id);


-- ---------------------------------------------------------------------------
-- 4. updated_at maintenance (reuses public.handle_updated_at from 001)
--    choices and exam_questions are rewritten wholesale by a reseed rather
--    than edited in place, so only questions carries the trigger.
-- ---------------------------------------------------------------------------
CREATE TRIGGER set_questions_updated_at
BEFORE UPDATE ON public.questions
FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
